//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoXIV.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EchoXIV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string PluginName { get { return ResourceManager.GetString("PluginName", resourceCulture); } }
        public static string Tab_General { get { return ResourceManager.GetString("Tab_General", resourceCulture); } }
        public static string Tab_ExcludedMessages { get { return ResourceManager.GetString("Tab_ExcludedMessages", resourceCulture); } }
        public static string Tab_Cache { get { return ResourceManager.GetString("Tab_Cache", resourceCulture); } }
        public static string Tab_IncomingChannels { get { return ResourceManager.GetString("Tab_IncomingChannels", resourceCulture); } }
        public static string Tab_History { get { return ResourceManager.GetString("Tab_History", resourceCulture); } }
        public static string General_Description { get { return ResourceManager.GetString("General_Description", resourceCulture); } }
        public static string General_EnableTranslation { get { return ResourceManager.GetString("General_EnableTranslation", resourceCulture); } }
        public static string General_SourceLanguage { get { return ResourceManager.GetString("General_SourceLanguage", resourceCulture); } }
        public static string General_TargetLanguage { get { return ResourceManager.GetString("General_TargetLanguage", resourceCulture); } }
        public static string General_DefaultChannel { get { return ResourceManager.GetString("General_DefaultChannel", resourceCulture); } }
        public static string General_DefaultChannelTip { get { return ResourceManager.GetString("General_DefaultChannelTip", resourceCulture); } }
        public static string Incoming_Description { get { return ResourceManager.GetString("Incoming_Description", resourceCulture); } }
        public static string Incoming_Enable { get { return ResourceManager.GetString("Incoming_Enable", resourceCulture); } }
        public static string Incoming_Disabled { get { return ResourceManager.GetString("Incoming_Disabled", resourceCulture); } }
        public static string Incoming_TranslateTo { get { return ResourceManager.GetString("Incoming_TranslateTo", resourceCulture); } }
        public static string Incoming_AutoDetectNote { get { return ResourceManager.GetString("Incoming_AutoDetectNote", resourceCulture); } }
        public static string Incoming_UseWritingLanguage { get { return ResourceManager.GetString("Incoming_UseWritingLanguage", resourceCulture); } }
        public static string Incoming_DisplayOptions { get { return ResourceManager.GetString("Incoming_DisplayOptions", resourceCulture); } }
        public static string Incoming_ShowOriginal { get { return ResourceManager.GetString("Incoming_ShowOriginal", resourceCulture); } }
        public static string Incoming_ShowTimestamps { get { return ResourceManager.GetString("Incoming_ShowTimestamps", resourceCulture); } }
        public static string Incoming_MaxMessages { get { return ResourceManager.GetString("Incoming_MaxMessages", resourceCulture); } }
        public static string Incoming_ChannelsToTranslate { get { return ResourceManager.GetString("Incoming_ChannelsToTranslate", resourceCulture); } }
        public static string Incoming_Linkshells { get { return ResourceManager.GetString("Incoming_Linkshells", resourceCulture); } }
        public static string Incoming_CrossWorldLS { get { return ResourceManager.GetString("Incoming_CrossWorldLS", resourceCulture); } }
        public static string Excluded_Description { get { return ResourceManager.GetString("Excluded_Description", resourceCulture); } }
        public static string Excluded_CurrentList { get { return ResourceManager.GetString("Excluded_CurrentList", resourceCulture); } }
        public static string Excluded_AddNew { get { return ResourceManager.GetString("Excluded_AddNew", resourceCulture); } }
        public static string Excluded_Add { get { return ResourceManager.GetString("Excluded_Add", resourceCulture); } }
        public static string Cache_Description { get { return ResourceManager.GetString("Cache_Description", resourceCulture); } }
        public static string Cache_Enable { get { return ResourceManager.GetString("Cache_Enable", resourceCulture); } }
        public static string Cache_Description_Long { get { return ResourceManager.GetString("Cache_Description_Long", resourceCulture); } }
        public static string Cache_MaxLength { get { return ResourceManager.GetString("Cache_MaxLength", resourceCulture); } }
        public static string Cache_Stats { get { return ResourceManager.GetString("Cache_Stats", resourceCulture); } }
        public static string Cache_Entries { get { return ResourceManager.GetString("Cache_Entries", resourceCulture); } }
        public static string Cache_Clear { get { return ResourceManager.GetString("Cache_Clear", resourceCulture); } }
        public static string Cache_ClearTooltip { get { return ResourceManager.GetString("Cache_ClearTooltip", resourceCulture); } }
        public static string Cache_Tip { get { return ResourceManager.GetString("Cache_Tip", resourceCulture); } }
        public static string ChatWindow_Title { get { return ResourceManager.GetString("ChatWindow_Title", resourceCulture); } }
        public static string ChatWindow_Active { get { return ResourceManager.GetString("ChatWindow_Active", resourceCulture); } }
        public static string ChatWindow_AutoScroll { get { return ResourceManager.GetString("ChatWindow_AutoScroll", resourceCulture); } }
        public static string ChatWindow_Clear { get { return ResourceManager.GetString("ChatWindow_Clear", resourceCulture); } }
        public static string ChatWindow_Translating { get { return ResourceManager.GetString("ChatWindow_Translating", resourceCulture); } }
        public static string ChatWindow_Original { get { return ResourceManager.GetString("ChatWindow_Original", resourceCulture); } }
        public static string Command_TranslationEnabled { get { return ResourceManager.GetString("Command_TranslationEnabled", resourceCulture); } }
        public static string Command_TranslationDisabled { get { return ResourceManager.GetString("Command_TranslationDisabled", resourceCulture); } }
        public static string Command_WindowOpened { get { return ResourceManager.GetString("Command_WindowOpened", resourceCulture); } }
        public static string Command_WindowClosed { get { return ResourceManager.GetString("Command_WindowClosed", resourceCulture); } }
        public static string Command_PositionReset { get { return ResourceManager.GetString("Command_PositionReset", resourceCulture); } }
        public static string Command_NoMessage { get { return ResourceManager.GetString("Command_NoMessage", resourceCulture); } }
        public static string Command_MessageTooLong { get { return ResourceManager.GetString("Command_MessageTooLong", resourceCulture); } }
        public static string Command_TranslateError { get { return ResourceManager.GetString("Command_TranslateError", resourceCulture); } }
        public static string Command_SendError { get { return ResourceManager.GetString("Command_SendError", resourceCulture); } }
        public static string General_ChangesAppliedImmediately { get { return ResourceManager.GetString("General_ChangesAppliedImmediately", resourceCulture); } }
        public static string Excluded_InputLabel { get { return ResourceManager.GetString("Excluded_InputLabel", resourceCulture); } }
        public static string Excluded_Remove { get { return ResourceManager.GetString("Excluded_Remove", resourceCulture); } }
        public static string Excluded_RestoreDefault { get { return ResourceManager.GetString("Excluded_RestoreDefault", resourceCulture); } }
        public static string Cache_CharLimit { get { return ResourceManager.GetString("Cache_CharLimit", resourceCulture); } }
        public static string Cache_PercentUsed { get { return ResourceManager.GetString("Cache_PercentUsed", resourceCulture); } }
        public static string Incoming_WindowOpacity { get { return ResourceManager.GetString("Incoming_WindowOpacity", resourceCulture); } }
        public static string Incoming_NativeWindow { get { return ResourceManager.GetString("Incoming_NativeWindow", resourceCulture); } }
        public static string Incoming_NativeWindowTooltip { get { return ResourceManager.GetString("Incoming_NativeWindowTooltip", resourceCulture); } }
        public static string Incoming_RestartNote { get { return ResourceManager.GetString("Incoming_RestartNote", resourceCulture); } }
        public static string Cache_DisabledWarning { get { return ResourceManager.GetString("Cache_DisabledWarning", resourceCulture); } }
        public static string ChatWindow_LockTooltip { get { return ResourceManager.GetString("ChatWindow_LockTooltip", resourceCulture); } }
        public static string ChatWindow_UnlockTooltip { get { return ResourceManager.GetString("ChatWindow_UnlockTooltip", resourceCulture); } }
        public static string ChatWindow_HideTooltip { get { return ResourceManager.GetString("ChatWindow_HideTooltip", resourceCulture); } }
        public static string ChatWindow_ClearTooltip { get { return ResourceManager.GetString("ChatWindow_ClearTooltip", resourceCulture); } }
        public static string ConfigWindow_Title { get { return ResourceManager.GetString("ConfigWindow_Title", resourceCulture); } }
        public static string Tab_Visuals { get { return ResourceManager.GetString("Tab_Visuals", resourceCulture); } }
        public static string General_Engine { get { return ResourceManager.GetString("General_Engine", resourceCulture); } }
        public static string General_EngineGoogleDesc { get { return ResourceManager.GetString("General_EngineGoogleDesc", resourceCulture); } }
        public static string General_EnginePapagoDesc { get { return ResourceManager.GetString("General_EnginePapagoDesc", resourceCulture); } }
        public static string General_WindowMode { get { return ResourceManager.GetString("General_WindowMode", resourceCulture); } }
        public static string General_RestoreWindow { get { return ResourceManager.GetString("General_RestoreWindow", resourceCulture); } }
        public static string General_RestoreWindowTip { get { return ResourceManager.GetString("General_RestoreWindowTip", resourceCulture); } }
        public static string General_SmartVisibility { get { return ResourceManager.GetString("General_SmartVisibility", resourceCulture); } }
        public static string General_SmartVisibilityTip { get { return ResourceManager.GetString("General_SmartVisibilityTip", resourceCulture); } }
        public static string General_VerboseLogs { get { return ResourceManager.GetString("General_VerboseLogs", resourceCulture); } }
        public static string General_VerboseLogsTip { get { return ResourceManager.GetString("General_VerboseLogsTip", resourceCulture); } }
        public static string Visuals_Description { get { return ResourceManager.GetString("Visuals_Description", resourceCulture); } }
        public static string Visuals_FontSize { get { return ResourceManager.GetString("Visuals_FontSize", resourceCulture); } }
        public static string Visuals_Spacing { get { return ResourceManager.GetString("Visuals_Spacing", resourceCulture); } }
        public static string Visuals_TimeFormat { get { return ResourceManager.GetString("Visuals_TimeFormat", resourceCulture); } }
        public static string Visuals_TimeFormatShort { get { return ResourceManager.GetString("Visuals_TimeFormatShort", resourceCulture); } }
        public static string Visuals_TimeFormatLong { get { return ResourceManager.GetString("Visuals_TimeFormatLong", resourceCulture); } }
        public static string Visuals_TimeFormatAMPM { get { return ResourceManager.GetString("Visuals_TimeFormatAMPM", resourceCulture); } }
        public static string Incoming_ShowOutgoing { get { return ResourceManager.GetString("Incoming_ShowOutgoing", resourceCulture); } }
        public static string WelcomeWindow_Title { get { return ResourceManager.GetString("WelcomeWindow_Title", resourceCulture); } }
        public static string Welcome_Intro { get { return ResourceManager.GetString("Welcome_Intro", resourceCulture); } }
        public static string Welcome_SourceQuestion { get { return ResourceManager.GetString("Welcome_SourceQuestion", resourceCulture); } }
        public static string Welcome_SourceTip { get { return ResourceManager.GetString("Welcome_SourceTip", resourceCulture); } }
        public static string Welcome_TargetQuestion { get { return ResourceManager.GetString("Welcome_TargetQuestion", resourceCulture); } }
        public static string Welcome_TargetTip { get { return ResourceManager.GetString("Welcome_TargetTip", resourceCulture); } }
        public static string Welcome_ReadQuestion { get { return ResourceManager.GetString("Welcome_ReadQuestion", resourceCulture); } }
        public static string Welcome_SaveStart { get { return ResourceManager.GetString("Welcome_SaveStart", resourceCulture); } }
        public static string Lang_ES { get { return ResourceManager.GetString("Lang_ES", resourceCulture); } }
        public static string Lang_EN { get { return ResourceManager.GetString("Lang_EN", resourceCulture); } }
        public static string Lang_JA { get { return ResourceManager.GetString("Lang_JA", resourceCulture); } }
        public static string Lang_FR { get { return ResourceManager.GetString("Lang_FR", resourceCulture); } }
        public static string Lang_DE { get { return ResourceManager.GetString("Lang_DE", resourceCulture); } }
        public static string Lang_PT { get { return ResourceManager.GetString("Lang_PT", resourceCulture); } }
        public static string Lang_KO { get { return ResourceManager.GetString("Lang_KO", resourceCulture); } }
        public static string Lang_ZH_Simp { get { return ResourceManager.GetString("Lang_ZH_Simp", resourceCulture); } }
        public static string Lang_ZH_Trad { get { return ResourceManager.GetString("Lang_ZH_Trad", resourceCulture); } }
        public static string Lang_RU { get { return ResourceManager.GetString("Lang_RU", resourceCulture); } }
        public static string Lang_IT { get { return ResourceManager.GetString("Lang_IT", resourceCulture); } }
        public static string Channel_Say { get { return ResourceManager.GetString("Channel_Say", resourceCulture); } }
        public static string Channel_Shout { get { return ResourceManager.GetString("Channel_Shout", resourceCulture); } }
        public static string Channel_Yell { get { return ResourceManager.GetString("Channel_Yell", resourceCulture); } }
        public static string Channel_Party { get { return ResourceManager.GetString("Channel_Party", resourceCulture); } }
        public static string Channel_Alliance { get { return ResourceManager.GetString("Channel_Alliance", resourceCulture); } }
        public static string Channel_FC { get { return ResourceManager.GetString("Channel_FC", resourceCulture); } }
        public static string Channel_NN { get { return ResourceManager.GetString("Channel_NN", resourceCulture); } }
        public static string Channel_Tell { get { return ResourceManager.GetString("Channel_Tell", resourceCulture); } }
        public static string Channel_Linkshell { get { return ResourceManager.GetString("Channel_Linkshell", resourceCulture); } }
        public static string Visuals_Colors { get { return ResourceManager.GetString("Visuals_Colors", resourceCulture); } }
        public static string Visuals_ChannelColorsDesc { get { return ResourceManager.GetString("Visuals_ChannelColorsDesc", resourceCulture); } }
        public static string History_Search { get { return ResourceManager.GetString("History_Search", resourceCulture); } }
        public static string History_NoMessages { get { return ResourceManager.GetString("History_NoMessages", resourceCulture); } }
        public static string History_Clear { get { return ResourceManager.GetString("History_Clear", resourceCulture); } }
        public static string History_Title { get { return ResourceManager.GetString("History_Title", resourceCulture); } }
        public static string Welcome_WindowModeQuestion { get { return ResourceManager.GetString("Welcome_WindowModeQuestion", resourceCulture); } }
        public static string Welcome_WindowModeWpf { get { return ResourceManager.GetString("Welcome_WindowModeWpf", resourceCulture); } }
        public static string Welcome_WindowModeImGui { get { return ResourceManager.GetString("Welcome_WindowModeImGui", resourceCulture); } }
        public static string Welcome_RecommendationFullscreen { get { return ResourceManager.GetString("Welcome_RecommendationFullscreen", resourceCulture); } }
        public static string Welcome_RecommendationWindowed { get { return ResourceManager.GetString("Welcome_RecommendationWindowed", resourceCulture); } }
    }
}
