//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoXIV.Properties {
    using System;
    using System.Globalization;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EchoXIV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        private static string GetString(string name)
        {
            return ResourceManager.GetString(name, resourceCulture)
                ?? ResourceManager.GetString(name, CultureInfo.InvariantCulture)
                ?? name;
        }

        public static string PluginName { get { return GetString("PluginName"); } }
        public static string Tab_General { get { return GetString("Tab_General"); } }
        public static string Tab_ExcludedMessages { get { return GetString("Tab_ExcludedMessages"); } }
        public static string Tab_Cache { get { return GetString("Tab_Cache"); } }
        public static string Tab_IncomingChannels { get { return GetString("Tab_IncomingChannels"); } }
        public static string Tab_History { get { return GetString("Tab_History"); } }
        public static string General_Description { get { return GetString("General_Description"); } }
        public static string General_EnableTranslation { get { return GetString("General_EnableTranslation"); } }
        public static string General_SourceLanguage { get { return GetString("General_SourceLanguage"); } }
        public static string General_TargetLanguage { get { return GetString("General_TargetLanguage"); } }
        public static string General_DefaultChannel { get { return GetString("General_DefaultChannel"); } }
        public static string General_DefaultChannelTip { get { return GetString("General_DefaultChannelTip"); } }
        public static string Incoming_Description { get { return GetString("Incoming_Description"); } }
        public static string Incoming_Enable { get { return GetString("Incoming_Enable"); } }
        public static string Incoming_Disabled { get { return GetString("Incoming_Disabled"); } }
        public static string Incoming_TranslateTo { get { return GetString("Incoming_TranslateTo"); } }
        public static string Incoming_AutoDetectNote { get { return GetString("Incoming_AutoDetectNote"); } }
        public static string Incoming_UseWritingLanguage { get { return GetString("Incoming_UseWritingLanguage"); } }
        public static string Incoming_DisplayOptions { get { return GetString("Incoming_DisplayOptions"); } }
        public static string Incoming_ShowOriginal { get { return GetString("Incoming_ShowOriginal"); } }
        public static string Incoming_ShowTimestamps { get { return GetString("Incoming_ShowTimestamps"); } }
        public static string Incoming_MaxMessages { get { return GetString("Incoming_MaxMessages"); } }
        public static string Incoming_ChannelsToTranslate { get { return GetString("Incoming_ChannelsToTranslate"); } }
        public static string Incoming_Linkshells { get { return GetString("Incoming_Linkshells"); } }
        public static string Incoming_CrossWorldLS { get { return GetString("Incoming_CrossWorldLS"); } }
        public static string Excluded_Description { get { return GetString("Excluded_Description"); } }
        public static string Excluded_CurrentList { get { return GetString("Excluded_CurrentList"); } }
        public static string Excluded_AddNew { get { return GetString("Excluded_AddNew"); } }
        public static string Excluded_Add { get { return GetString("Excluded_Add"); } }
        public static string Cache_Description { get { return GetString("Cache_Description"); } }
        public static string Cache_Enable { get { return GetString("Cache_Enable"); } }
        public static string Cache_Description_Long { get { return GetString("Cache_Description_Long"); } }
        public static string Cache_MaxLength { get { return GetString("Cache_MaxLength"); } }
        public static string Cache_Stats { get { return GetString("Cache_Stats"); } }
        public static string Cache_Entries { get { return GetString("Cache_Entries"); } }
        public static string Cache_Clear { get { return GetString("Cache_Clear"); } }
        public static string Cache_ClearTooltip { get { return GetString("Cache_ClearTooltip"); } }
        public static string Cache_Tip { get { return GetString("Cache_Tip"); } }
        public static string ChatWindow_Title { get { return GetString("ChatWindow_Title"); } }
        public static string ChatWindow_Active { get { return GetString("ChatWindow_Active"); } }
        public static string ChatWindow_AutoScroll { get { return GetString("ChatWindow_AutoScroll"); } }
        public static string ChatWindow_Clear { get { return GetString("ChatWindow_Clear"); } }
        public static string ChatWindow_Translating { get { return GetString("ChatWindow_Translating"); } }
        public static string ChatWindow_Original { get { return GetString("ChatWindow_Original"); } }
        public static string Command_TranslationEnabled { get { return GetString("Command_TranslationEnabled"); } }
        public static string Command_TranslationDisabled { get { return GetString("Command_TranslationDisabled"); } }
        public static string Command_WindowOpened { get { return GetString("Command_WindowOpened"); } }
        public static string Command_WindowClosed { get { return GetString("Command_WindowClosed"); } }
        public static string Command_PositionReset { get { return GetString("Command_PositionReset"); } }
        public static string Command_NoMessage { get { return GetString("Command_NoMessage"); } }
        public static string Command_MessageTooLong { get { return GetString("Command_MessageTooLong"); } }
        public static string Command_TranslateError { get { return GetString("Command_TranslateError"); } }
        public static string Command_SendError { get { return GetString("Command_SendError"); } }
        public static string Command_DalamudWindowOnly { get { return GetString("Command_DalamudWindowOnly"); } }
        public static string General_ChangesAppliedImmediately { get { return GetString("General_ChangesAppliedImmediately"); } }
        public static string Excluded_InputLabel { get { return GetString("Excluded_InputLabel"); } }
        public static string Excluded_Remove { get { return GetString("Excluded_Remove"); } }
        public static string Excluded_RestoreDefault { get { return GetString("Excluded_RestoreDefault"); } }
        public static string Cache_CharLimit { get { return GetString("Cache_CharLimit"); } }
        public static string Cache_PercentUsed { get { return GetString("Cache_PercentUsed"); } }
        public static string Cache_DisabledWarning { get { return GetString("Cache_DisabledWarning"); } }
        public static string ChatWindow_LockTooltip { get { return GetString("ChatWindow_LockTooltip"); } }
        public static string ChatWindow_UnlockTooltip { get { return GetString("ChatWindow_UnlockTooltip"); } }
        public static string ChatWindow_HideTooltip { get { return GetString("ChatWindow_HideTooltip"); } }
        public static string ChatWindow_ClearTooltip { get { return GetString("ChatWindow_ClearTooltip"); } }
        public static string ConfigWindow_Title { get { return GetString("ConfigWindow_Title"); } }
        public static string Tab_Visuals { get { return GetString("Tab_Visuals"); } }
        public static string General_Engine { get { return GetString("General_Engine"); } }
        public static string General_EngineGoogleDesc { get { return GetString("General_EngineGoogleDesc"); } }
        public static string General_EnginePapagoDesc { get { return GetString("General_EnginePapagoDesc"); } }
        public static string General_VerboseLogs { get { return GetString("General_VerboseLogs"); } }
        public static string General_VerboseLogsTip { get { return GetString("General_VerboseLogsTip"); } }
        public static string Visuals_Description { get { return GetString("Visuals_Description"); } }
        public static string Visuals_FontSize { get { return GetString("Visuals_FontSize"); } }
        public static string Visuals_Spacing { get { return GetString("Visuals_Spacing"); } }
        public static string Visuals_TimeFormat { get { return GetString("Visuals_TimeFormat"); } }
        public static string Visuals_TimeFormatShort { get { return GetString("Visuals_TimeFormatShort"); } }
        public static string Visuals_TimeFormatLong { get { return GetString("Visuals_TimeFormatLong"); } }
        public static string Visuals_TimeFormatAMPM { get { return GetString("Visuals_TimeFormatAMPM"); } }
        public static string Incoming_ShowOutgoing { get { return GetString("Incoming_ShowOutgoing"); } }
        public static string WelcomeWindow_Title { get { return GetString("WelcomeWindow_Title"); } }
        public static string Welcome_Intro { get { return GetString("Welcome_Intro"); } }
        public static string Welcome_SourceQuestion { get { return GetString("Welcome_SourceQuestion"); } }
        public static string Welcome_SourceTip { get { return GetString("Welcome_SourceTip"); } }
        public static string Welcome_TargetQuestion { get { return GetString("Welcome_TargetQuestion"); } }
        public static string Welcome_TargetTip { get { return GetString("Welcome_TargetTip"); } }
        public static string Welcome_ReadQuestion { get { return GetString("Welcome_ReadQuestion"); } }
        public static string Welcome_SaveStart { get { return GetString("Welcome_SaveStart"); } }
        public static string Lang_ES { get { return GetString("Lang_ES"); } }
        public static string Lang_EN { get { return GetString("Lang_EN"); } }
        public static string Lang_JA { get { return GetString("Lang_JA"); } }
        public static string Lang_FR { get { return GetString("Lang_FR"); } }
        public static string Lang_DE { get { return GetString("Lang_DE"); } }
        public static string Lang_PT { get { return GetString("Lang_PT"); } }
        public static string Lang_KO { get { return GetString("Lang_KO"); } }
        public static string Lang_NO { get { return GetString("Lang_NO"); } }
        public static string Lang_ZH_Simp { get { return GetString("Lang_ZH_Simp"); } }
        public static string Lang_ZH_Trad { get { return GetString("Lang_ZH_Trad"); } }
        public static string Lang_RU { get { return GetString("Lang_RU"); } }
        public static string Lang_IT { get { return GetString("Lang_IT"); } }
        public static string Channel_Say { get { return GetString("Channel_Say"); } }
        public static string Channel_Shout { get { return GetString("Channel_Shout"); } }
        public static string Channel_Yell { get { return GetString("Channel_Yell"); } }
        public static string Channel_Party { get { return GetString("Channel_Party"); } }
        public static string Channel_Alliance { get { return GetString("Channel_Alliance"); } }
        public static string Channel_FC { get { return GetString("Channel_FC"); } }
        public static string Channel_NN { get { return GetString("Channel_NN"); } }
        public static string Channel_Tell { get { return GetString("Channel_Tell"); } }
        public static string Channel_Linkshell { get { return GetString("Channel_Linkshell"); } }
        public static string Visuals_Colors { get { return GetString("Visuals_Colors"); } }
        public static string Visuals_ChannelColorsDesc { get { return GetString("Visuals_ChannelColorsDesc"); } }
        public static string History_Search { get { return GetString("History_Search"); } }
        public static string History_NoMessages { get { return GetString("History_NoMessages"); } }
        public static string History_Clear { get { return GetString("History_Clear"); } }
        public static string History_Title { get { return GetString("History_Title"); } }
        public static string ChatWindow_Retry { get { return GetString("ChatWindow_Retry"); } }
        public static string ChatWindow_RetryTooltip { get { return GetString("ChatWindow_RetryTooltip"); } }
    }
}
